### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by farooqkz** [farooqkz/KaiUIng#8]
This will help a lot in reducing bugs. I will do it myself as I have to learn.

**Comment by Simon-Laux** [comment]
some points we need to have:

## Basics
- [ ] files with TS need to be called `.tsx` if they contain jsx tags (html tags in js)
- [ ] tsconfig should have the following compiler options:
```js
// if you have an any type you need to write it out
"noImplicitAny": true,
 // makes us handle null and undefined cases, without it ts will only be half as useful
"strictNullChecks": true,
"strict": true
```
for more compiler options see https://www.typescriptlang.org/tsconfig#compilerOptions

## Testing
- [ ] add yarn script in package json that calls `tsc --noEmit` (real typescript compiler) to test for type errors, might be that parcel uses some faster way to translate typescript that doesn't do all checks.
- [ ] add this to the testing CI

**Comment by farooqkz** [comment]
Related: https://github.com/jhsware/inferno-parcel-templates

**Comment by farooqkz** [comment]
Related: https://github.com/infernojs/inferno/issues/1619

**Comment by farooqkz** [comment]
Part of it has been done. Commits to master.
